"""Added unique parameter for name in subscription table

Revision ID: 152c33d238dc
Revises: be01ae866903
Create Date: 2024-05-23 16:16:36.764551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '152c33d238dc'
down_revision: Union[str, None] = 'be01ae866903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_subscription_name_owner', 'subscription', ['name', 'owner_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_subscription_name_owner', 'subscription', type_='unique')
    # ### end Alembic commands ###
